xcodeproj 'RMErrorsTests'
workspace '../RMErrors'
use_frameworks!

def common_pods
  pod 'RMErrors', :path => '../'
end

target :ios do
  platform :ios, '8.0'
  link_with 'RMErrorsIOSTests'
  common_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'RMErrorsOSXTests'
  common_pods
end

